### PR TITLE
Home

### PR DESCRIPTION
**Pull request by federico101**

### CODE REVIEW

**Review by lrnzdc3696 — CHANGES_REQUESTED** [review]
You could add the forms style in the css rather than making it an internal css

**Comment by federico101** [comment]
> You could add the forms style in the css rather than making it an internal css

pauna lang muna para magfit siya dun sa navbar

**Comment by lrnzdc3696** [comment]
Wdym?

**Comment by federico101** [comment]
> Wdym?

the navbar covers the contents of the other pages so i used the style property for the meantime just to adjust the contents

**Comment by lrnzdc3696** [comment]
You could put the contents of the style
```html
<style>
  .forms{
    ...
  }
</style>
```
into the css file...

**Comment by lrnzdc3696** [comment]
Just make sure you fix that in the future

**Pull request merged**
